WIP: Move `XCTAssertStringHasMinimalCount` to `XCTestExtensions`
Warning: this commit doesn't build:

```
XCTestExtensions/XCTestExtensions/XCTestExtensions.swift:18:17: error: use of unresolved identifier 'XCTUnwrap'
    let s = try XCTUnwrap(s, "Expected string to have at least \(minCount) characters, but it was nil: \(message())", file: file, line: line)
                ^~~~~~~~~
```